# Space Debris Orbit Propogation Computation Using Python-sgp4 with TLE Data

In [13]:
# Import necessary modules 

from sgp4.api import jday, Satrec, SatrecArray
import numpy as np

In [3]:
# Sample TLE data

TLE_sample =['1     5U 58002B   20201.85549302 +.00000094 +00000-0 +12744-3 0  9995',
             '2     5 034.2442 128.4695 1846568 138.1306 237.6298 10.84859958208779',
             '1    11U 59001A   20201.67905296 -.00000121 +00000-0 -59347-4 0  9994',
             '2    11 032.8677 294.3993 1468339 073.3889 302.2437 11.85689364278805',
             '1    12U 59001B   20201.77153551 +.00000121 +00000-0 +49752-4 0  9992',
             '2    12 032.9071 237.8878 1664845 245.8540 095.9419 11.44295189283680',
             '1    16U 58002A   20201.90299360 -.00000104 +00000-0 -12833-3 0  9992',
             '2    16 034.2645 060.8714 2024011 014.5580 350.5473 10.48681631462245',
             '1    20U 59007A   20201.87239646 +.00000141 +00000-0 +65965-4 0  9994',
             '2    20 033.3437 066.5809 1664755 078.7021 299.5311 11.55695870234354',
             '1    22U 59009A   20202.18388500 -.00000167  00000-0  11090-4 0  9996',
             '2    22  50.2845 308.4922 0139458  23.8072 336.9244 14.95162025230225',
             '1    29U 60002B   20201.92877026 -.00000176 +00000-0 +48809-5 0  9994',
             '2    29 048.3788 155.3566 0024047 009.8486 350.2893 14.74363420223331',
             '1    45U 60007A   20201.67486477 -.00000054  00000-0  13835-4 0  9990',
             '2    45  66.6952 296.0033 0262497 291.5541  65.7769 14.33681662127320',
             '1    46U 60007B   20201.76063733 -.00000063  00000-0  10472-4 0  9991',
             '2    46  66.6916 319.2249 0202838 107.8136 254.5215 14.49304964143786',
             '1    47U 60007C   20201.88040715 -.00000057 +00000-0 +12616-4 0  9995',
             '2    47 066.6660 068.3035 0235338 279.2337 078.2220 14.42093623139351',
             '1    50U 60009B   20201.82308180 -.00000077  00000-0  92011-4 0  9997',
             '2    50  47.2329  20.8070 0113804  62.2290 298.9985 12.20112425674635',
             '1    51U 60009C   20201.87415440 -.00000079 +00000-0 +43379-4 0  9996',
             '2    51 047.2118 247.1209 0108729 259.1072 099.7465 12.18276338668044',
             '1    53U 60009E   20202.18147685 -.00000020  00000-0  63963-3 0  9992',
             '2    53  47.2748 158.0586 0097159 178.8957 181.2061 12.17242562672557',
             '1    58U 60013A   20201.90281353 +.00000107 +00000-0 +34929-4 0  9998',
             '2    58 028.3282 290.0115 0165064 337.9232 021.4270 13.46322919942998',
             '1    59U 60013B   20201.86077292 +.00000102 +00000-0 +14394-4 0  9998',
             '2    59 028.2504 051.7335 0189268 198.2074 161.1619 13.52977694950996',
             '1    82U 61004B   20201.90812855 -.00000058 +00000-0 -22566-4 0  9994',
             '2    82 038.8645 078.2037 1175013 240.2720 107.6006 12.26062552811795',
             '1    85U 61004C   20201.35864063 +.00001614 +00000-0 +36342-3 0  9997',
             '2    85 038.7689 218.3025 0388081 353.5264 006.0560 14.20819606935633',
             '1   107U 61013A   20202.11198896  .00000197  00000-0  84114-5 0  9998',
             '2   107  28.7888 357.0085 0546802  37.6714 326.0892 14.08972284970384',
             '1   115U 60002D   20201.85251533 -.00000117 +00000-0 +13315-4 0  9999',
             '2   115 048.1665 118.4368 0034577 030.3985 329.8924 14.83591231196622',
             '1   116U 61015A   20202.16967729 -.00000048  00000-0  22062-4 0  9993',
             '2   116  66.8101 128.2415 0077699 340.8668  18.9497 13.91772786996854',
             '1   117U 61015B   20201.77521712 -.00000053 +00000-0 +18361-4 0  9991',
             '2   117 066.8106 225.2976 0077279 002.0127 358.1247 13.89853765994114',
             '1   118U 61015C   20201.83021088 -.00000061 +00000-0 +11483-4 0  9997',
             '2   118 066.7646 038.6779 0084211 346.2102 013.6681 14.01681762013602',
             '1   119U 61015D   20202.19033630 -.00000034  00000-0  20984-4 0  9990',
             '2   119  66.7269 219.3078 0102246  16.2604 344.1730 14.23298353 51348',
             '1   120U 61015E   20201.68298101 -.00000018  00000-0  26471-4 0  9990',
             '2   120  66.7070 289.1657 0110966 124.8307 236.3287 14.25400844 40813',
             '1   121U 61015F   20202.13786155 -.00000079  00000-0  96292-7 0  9991',
             '2   121  66.7486   3.1298 0086675  70.4922 290.5498 13.99692183 24297',
             '1   122U 61015G   20202.20465887  .00000156  00000-0  44241-4 0  9995',
             '2   122  66.7505 155.6249 0064217 115.2196 245.5599 14.69226418 96011',
             '1   123U 61015H   20201.80863507 -.00000008 +00000-0 +26211-4 0  9996',
             '2   123 066.6856 038.7720 0109809 044.8362 316.1546 14.37074102069040',
             '1   124U 61015J   20201.92526444 +.00000100 +00000-0 +69296-4 0  9998',
             '2   124 066.5422 188.3927 0079143 194.8013 165.0767 14.30497649049790',
             '1   125U 61015K   20201.68187891  .00000079  00000-0  94482-4 0  9991',
             '2   125  66.8767 281.1114 0078936 208.0386 151.6439 14.05515991 14237',
             '1   126U 61015L   20201.89105670 +.00000091 +00000-0 +59646-4 0  9997',
             '2   126 066.7130 062.6551 0062171 041.4120 319.1669 14.36256434054000',
             '1   127U 61015M   20201.90618549 +.00000216 +00000-0 +95580-4 0  9990',
             '2   127 066.8307 274.0351 0079448 224.2279 135.2458 14.38777980055624',
             '1   128U 61015N   20202.07007440 -.00000068  00000-0  76092-5 0  9996',
             '2   128  66.6742 172.0415 0094942 353.4895   6.4946 14.01193879 13072',
             '1   130U 61015Q   20201.95016255 -.00000054 +00000-0 +16538-4 0  9992',
             '2   130 066.7692 200.4469 0085749 359.3418 000.7537 13.98714704009569',
             '1   131U 61015R   20202.08769052 -.00000022  00000-0  37151-4 0  9997',
             '2   131  66.7358  78.6111 0076368 137.5366 223.1660 14.00690734  1608',
             '1   132U 61015S   20201.87760607 -.00000043 +00000-0 +26247-4 0  9998',
             '2   132 066.6596 264.5345 0078637 210.4581 149.1919 13.94322028002737',
             '1   133U 61015T   20201.64575725 -.00000205 +00000-0 -60203-4 0  9990',
             '2   133 067.1164 280.0569 0047893 054.6159 305.9396 14.18207967027026',
             '1   134U 61015U   20201.78166607 -.00000026 +00000-0 +35850-4 0  9991',
             '2   134 066.8816 316.0434 0087814 305.2162 054.0722 13.96833990004176',
             '1   136U 61015W   20201.91500821 +.00000174 +00000-0 +89787-4 0  9999',
             '2   136 067.5306 034.6977 0058453 201.7147 158.1481 14.33590750046759',
             '1   138U 61015Y   20202.14927904 -.00000092  00000-0 -10242-4 0  9993',
             '2   138  67.1559 359.8060 0030806 356.3272   3.7584 14.01717302   578',
             '1   141U 61015AB  20201.68255742 -.00000041  00000-0  30958-4 0  9998',
             '2   141  66.5898 291.8031 0053237   8.2024 351.9909 13.86874752972689',
             '1   144U 61015AE  20201.76621550 -.00000021 +00000-0 +46341-4 0  9995',
             '2   144 066.5013 321.2096 0049615 292.7938 066.7901 13.90092074984533',
             '1   145U 61015AF  20201.74676040 -.00000093  00000-0 -10009-4 0  9990',
             '2   145  66.9278 325.3048 0056677  85.6724 275.0834 14.01345807 14601',
             '1   147U 61015AH  20201.90812668 +.00000272 +00000-0 +16795-3 0  9992',
             '2   147 066.6177 181.9270 0051025 148.6139 211.8016 14.19097401027813',
             '1   148U 61015AJ  20202.19363407  .00000289  00000-0  20724-3 0  9992',
             '2   148  65.7765   0.2205 0154378 335.0188  24.3472 14.05725433455747',
             '1   150U 61015AL  20201.90141820 +.00000006 +00000-0 +79204-4 0  9991',
             '2   150 066.2475 173.9335 0053724 064.1926 296.4671 13.81242787810207',
             '1   152U 61015AN  20202.02517057 -.00000183  00000-0 -51021-4 0  9991',
             '2   152  66.5895  48.4471 0160236 223.8107 135.0179 14.09234393 21791',
             '1   154U 61015AQ  20202.23320816 -.00000099  00000-0 -11427-4 0  9993',
             '2   154  66.6574 181.4014 0077670  52.4291 308.3815 14.04482603 13863',
             '1   155U 61015AR  20201.82961614  .00000261  00000-0  11045-3 0  9999',
             '2   155  66.8791 236.8913 0041508 142.9833 217.4148 14.39301754 50043',
             '1   158U 61015AU  20202.17084700  .00000233  00000-0  74498-3 0  9993',
             '2   158  67.0736 105.0155 0605062 113.8706 252.6907 12.65254337732255',
             '1   159U 61015AV  20201.80328252 +.00000205 +00000-0 +62650-3 0  9992',
             '2   159 065.5264 322.6398 0380807 261.0579 094.7165 13.02061197799753']

In [15]:
# Loop through the TLE data to create a SatrecArray with several individual space objects 

satellites = []  # SatrecArray to store all space objects 

for i in range(0, len(TLE_sample), 2):
    line1 = TLE_sample[i]
    line2 = TLE_sample[i+1]
    
    # Check to see if the Elset Classification is 'U' indicating that it is an unclassified object, that is, a space debris 
    if TLE_sample[i].split()[1][-1] == 'U':
        satellites.append(Satrec.twoline2rv(line1, line2))

satA = SatrecArray(satellites)

In [20]:
# Handle the Julian dates for an arbitrary date

jd, fr = jday(2020, 8, 20, 12, 0, 0)

# Convert to numpy array 
jd = np.array([jd])
fr = np.array([fr])

In [21]:
# Use sgp4 to compute the error, position (TEME: True Equator Mean Equinox), and velocity

err, r, v = satA.sgp4(jd, fr)

In [25]:
err

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=uint8)

In [26]:
r

array([[[ 1840.53487763, -5628.73203571, -3928.11549069]],

       [[-4984.55172561,  4789.33946799, -2796.58241534]],

       [[ 6299.08168529, -6629.02836012,  -682.8251063 ]],

       [[-2108.40330835, -7982.96985915, -5416.76755701]],

       [[ 8203.7133267 , -3515.30367807,  2281.74822079]],

       [[ 6562.30129164,  -308.30858836, -2154.17341629]],

       [[ 4555.70481775, -3294.75783238, -4245.32600122]],

       [[ -367.63847937, -3504.73903404,  6428.89226638]],

       [[-4807.52592896, -4603.52424614, -2614.10296031]],

       [[ 5591.32716915, -3032.33879176, -3128.21002832]],

       [[-5157.56696689, -1809.20429601, -5863.97292024]],

       [[ 7442.09520581, -2566.61839642, -1725.4703866 ]],

       [[-4450.44202216, -6589.66476367,   823.86088623]],

       [[-7055.73824426,  1039.63123214,  2564.12869228]],

       [[-6789.98578965,  -264.41195404, -3359.69122605]],

       [[-6062.0714203 , -3327.28417623, -5147.20197719]],

       [[-5133.64953077,  2501.03739387,

In [27]:
v

array([[[ 7.3498071 ,  3.40092551, -0.59085193]],

       [[-6.22254269, -3.50803818,  2.61455721]],

       [[ 4.17568663,  3.17450253, -3.39589238]],

       [[ 5.28584998, -2.74622019,  0.20442603]],

       [[ 2.04177927,  4.88973953,  3.20101841]],

       [[-1.42411423,  5.19525527, -5.39028267]],

       [[ 5.69896791,  3.59413735,  3.31954037]],

       [[ 6.33654519,  2.95325821,  2.02837987]],

       [[ 0.50906406, -3.89135421,  6.3255797 ]],

       [[ 4.33112106,  1.42617269,  5.98240828]],

       [[ 1.84729241, -6.7726202 ,  0.36793085]],

       [[ 0.54326573,  4.96001893, -4.90819948]],

       [[ 3.72576207, -3.08319631, -5.14140337]],

       [[-0.15401533, -6.78306591,  2.40376614]],

       [[-0.29805611, -7.07690586,  1.19757347]],

       [[ 4.21505005, -4.86530242, -0.93010479]],

       [[-3.44700489, -6.45256028, -0.77975303]],

       [[ 2.98965306, -6.16493322,  3.38342963]],

       [[ 5.73319445,  1.23325249,  4.71187874]],

       [[-1.88651364,  2.314970